# site settings
title: Bui
subtitle:
email:
description: Hi, Happy Birthday! I kinda wrote letters for you and I thought adding it like this here is a little nicer than giving the google doc link so, here it is. I was also going to do this music thing, but I could not, since things came up and I am a little slow with everything. Anyway, I love you so much sir, Happy Birthday again!
baseurl: "/bui" # the subpath of your site, e.g. /blog
url: "https://beelcone.github.io" # the base hostname & protocol for your site
author: Lisa
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
# tiles-source: pages # accepts "posts" or "pages"
tiles-source: posts # accepts "posts" or "pages"
# vtiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
